language: rust
dist: xenial
rust:
  - nightly
cache: cargo
before_install:
  - sudo apt-get update
  - sudo apt-get install libglfw3-dev -y # And all dependencies
script:
  - cargo build # Test dev build
  # - cargo test # Not yet!