[package]
name = "rust_chess"
version = "0.1.0"
authors = ["Lev <lev.kokotov@gmail.com>"]

[dependencies]
colored = "1.6"
regex = "0.2"
lazy_static = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
kiss3d = "*"